# build image
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /source

ENV HUSKY=0

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o /app --no-restore

# runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build-env /app .
ENTRYPOINT ["dotnet", "AccountTransactions.Api.dll"]